version: '3.3'
services:
  petclinic-mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Cam.Caltech13!
      MYSQL_DATABASE: pet_clinic
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  petclinic-springboot-container:
    build: ./PetClinic/petclinic/
    depends_on:
      - petclinic-mysql-container
    ports:
      - 8181:8080
    restart: always
  petclinic-angular-container:
    build: ./petclinic-frontend/
    ports:
      - 83:80